stages:
# Data Preprocessing Stage
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/heart.csv
    - src/preprocess.py
    params:
    - preprocess.random_state
    - preprocess.test_size
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
# Model Training Stage
  train:
    cmd: python src/train.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - src/train.py
    params:
    - train
    outs:
    - models/model.pkl
    metrics:
    - metrics/metrics.json:
        cache: false
